default_context:
  project_name: 'rock-keyword-history'
  project_slug: 'rock-keyword-history'
  domain_main: 'keyword.history.rockcontent.com'
  domain_staging: 'stag.keyword.history.rockcontent.com'
  docker_swarm_stack_name_main: 'keyword-history-rockcontent-com'
  docker_swarm_stack_name_staging: 'stag-keyword-history-rockcontent-com'
  secret_key: 'q234adsfjasklj324123rsdfa975234sdgfkjahgsdfja'
  first_superuser: 'rock.analytics@rockcontent.com'
  first_superuser_password: 'Slashdot!23'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.keyword.history.rockcontent.com", "https://stag.keyword.history.rockcontent.com", "https://keyword.history.rockcontent.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'rock.analytics@rockcontent.com'
  postgres_password: 'tulio'
  pgadmin_default_user: 'rock.analytics@rockcontent.com'
  pgadmin_default_user_password: 'Slashdot!23'
  traefik_constraint_tag: 'keyword.history.rockcontent.com'
  traefik_constraint_tag_staging: 'stag.keyword.history.rockcontent.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Slashdot!23'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
