"""Remove column url from model PhraseAdwords

Revision ID: 00994d6cdb17
Revises: c1c9dc2279a2
Create Date: 2020-07-07 20:47:52.267685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00994d6cdb17'
down_revision = 'c1c9dc2279a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phraseadwords_url', table_name='phraseadwords')
    op.drop_column('phraseadwords', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phraseadwords', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_phraseadwords_url', 'phraseadwords', ['url'], unique=False)
    # ### end Alembic commands ###
