"""Remove field data from model Log

Revision ID: 01265ebe7947
Revises: 0f575595d17c
Create Date: 2020-07-24 10:51:35.423142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01265ebe7947'
down_revision = '0f575595d17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
