"""Add model Log

Revision ID: 0f575595d17c
Revises: 583eccbb7227
Create Date: 2020-07-24 10:28:41.038441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f575595d17c'
down_revision = '583eccbb7227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('search_data', sa.String(), nullable=False),
    sa.Column('search_type', sa.String(), nullable=False),
    sa.Column('num_rows', sa.Integer(), nullable=False),
    sa.Column('source_response', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=False)
    op.create_index(op.f('ix_log_search_data'), 'log', ['search_data'], unique=False)
    op.create_index(op.f('ix_log_search_type'), 'log', ['search_type'], unique=False)
    op.create_index(op.f('ix_log_source_response'), 'log', ['source_response'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_source_response'), table_name='log')
    op.drop_index(op.f('ix_log_search_type'), table_name='log')
    op.drop_index(op.f('ix_log_search_data'), table_name='log')
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
