"""Create model domain organic

Revision ID: 11c92170c4da
Revises: 2ac9a4168d3b
Create Date: 2020-07-14 21:51:39.893639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c92170c4da'
down_revision = '2ac9a4168d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domainorganic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.DECIMAL(), nullable=False),
    sa.Column('competition', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('previous_position', sa.Integer(), nullable=False),
    sa.Column('position_difference', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('traffic', sa.DECIMAL(), nullable=False),
    sa.Column('traffic_cost', sa.DECIMAL(), nullable=False),
    sa.Column('number_results', sa.Integer(), nullable=False),
    sa.Column('trends', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domainorganic_database'), 'domainorganic', ['database'], unique=False)
    op.create_index(op.f('ix_domainorganic_domain'), 'domainorganic', ['domain'], unique=False)
    op.create_index(op.f('ix_domainorganic_id'), 'domainorganic', ['id'], unique=False)
    op.create_index(op.f('ix_domainorganic_keyword'), 'domainorganic', ['keyword'], unique=False)
    op.create_index(op.f('ix_domainorganic_trends'), 'domainorganic', ['trends'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domainorganic_trends'), table_name='domainorganic')
    op.drop_index(op.f('ix_domainorganic_keyword'), table_name='domainorganic')
    op.drop_index(op.f('ix_domainorganic_id'), table_name='domainorganic')
    op.drop_index(op.f('ix_domainorganic_domain'), table_name='domainorganic')
    op.drop_index(op.f('ix_domainorganic_database'), table_name='domainorganic')
    op.drop_table('domainorganic')
    # ### end Alembic commands ###
