"""Add column keyword_search in model PhraseFullsearch

Revision ID: 17f3ee828e1b
Revises: 5bbbf62fd2a5
Create Date: 2020-07-07 17:58:37.885271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f3ee828e1b'
down_revision = '5bbbf62fd2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrasefullsearch', sa.Column('keyword_search', sa.String(), nullable=False))
    op.create_index(op.f('ix_phrasefullsearch_keyword_search'), 'phrasefullsearch', ['keyword_search'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasefullsearch_keyword_search'), table_name='phrasefullsearch')
    op.drop_column('phrasefullsearch', 'keyword_search')
    # ### end Alembic commands ###
