"""Add phrase_fullsearch model

Revision ID: 28f41b39019e
Revises: a0228fef1142
Create Date: 2020-07-03 19:23:55.226955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f41b39019e'
down_revision = 'a0228fef1142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrasefullsearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('number_results', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.DECIMAL(), nullable=False),
    sa.Column('competition', sa.Integer(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=False),
    sa.Column('trends', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrasefullsearch_id'), 'phrasefullsearch', ['id'], unique=False)
    op.create_index(op.f('ix_phrasefullsearch_keyword'), 'phrasefullsearch', ['keyword'], unique=False)
    op.create_index(op.f('ix_phrasefullsearch_trends'), 'phrasefullsearch', ['trends'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasefullsearch_trends'), table_name='phrasefullsearch')
    op.drop_index(op.f('ix_phrasefullsearch_keyword'), table_name='phrasefullsearch')
    op.drop_index(op.f('ix_phrasefullsearch_id'), table_name='phrasefullsearch')
    op.drop_table('phrasefullsearch')
    # ### end Alembic commands ###
