"""Add phrase_all model

Revision ID: 2c0404bf8969
Revises: b3c34efb3d21
Create Date: 2020-07-03 18:34:48.293082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0404bf8969'
down_revision = 'b3c34efb3d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phraseall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phraseall_database'), 'phraseall', ['database'], unique=False)
    op.create_index(op.f('ix_phraseall_id'), 'phraseall', ['id'], unique=False)
    op.create_index(op.f('ix_phraseall_keyword'), 'phraseall', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phraseall_keyword'), table_name='phraseall')
    op.drop_index(op.f('ix_phraseall_id'), table_name='phraseall')
    op.drop_index(op.f('ix_phraseall_database'), table_name='phraseall')
    op.drop_table('phraseall')
    # ### end Alembic commands ###
