"""Add phrase_adwords model

Revision ID: 3eaa1e2dd2ee
Revises: befe121d7351
Create Date: 2020-07-03 19:44:19.388122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eaa1e2dd2ee'
down_revision = 'befe121d7351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phraseadwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('visible_url', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phraseadwords_domain'), 'phraseadwords', ['domain'], unique=False)
    op.create_index(op.f('ix_phraseadwords_id'), 'phraseadwords', ['id'], unique=False)
    op.create_index(op.f('ix_phraseadwords_keyword'), 'phraseadwords', ['keyword'], unique=False)
    op.create_index(op.f('ix_phraseadwords_url'), 'phraseadwords', ['url'], unique=False)
    op.create_index(op.f('ix_phraseadwords_visible_url'), 'phraseadwords', ['visible_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phraseadwords_visible_url'), table_name='phraseadwords')
    op.drop_index(op.f('ix_phraseadwords_url'), table_name='phraseadwords')
    op.drop_index(op.f('ix_phraseadwords_keyword'), table_name='phraseadwords')
    op.drop_index(op.f('ix_phraseadwords_id'), table_name='phraseadwords')
    op.drop_index(op.f('ix_phraseadwords_domain'), table_name='phraseadwords')
    op.drop_table('phraseadwords')
    # ### end Alembic commands ###
