"""Generate table Phrasethis

Revision ID: 421a8c42227b
Revises: e4f08d107e8c
Create Date: 2020-07-07 20:26:34.636874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421a8c42227b'
down_revision = 'e4f08d107e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrasethis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.DECIMAL(), nullable=False),
    sa.Column('competition', sa.Integer(), nullable=False),
    sa.Column('number_results', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrasethis_database'), 'phrasethis', ['database'], unique=False)
    op.create_index(op.f('ix_phrasethis_id'), 'phrasethis', ['id'], unique=False)
    op.create_index(op.f('ix_phrasethis_keyword'), 'phrasethis', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasethis_keyword'), table_name='phrasethis')
    op.drop_index(op.f('ix_phrasethis_id'), table_name='phrasethis')
    op.drop_index(op.f('ix_phrasethis_database'), table_name='phrasethis')
    op.drop_table('phrasethis')
    # ### end Alembic commands ###
