"""Add phrase_adword_historical model

Revision ID: 511c9767ed95
Revises: c42bfeca679e
Create Date: 2020-07-03 19:54:40.435968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511c9767ed95'
down_revision = 'c42bfeca679e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
