"""Add new field database in model FullSearch

Revision ID: 57814115f909
Revises: cd84cf951654
Create Date: 2020-07-06 11:47:21.397624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57814115f909'
down_revision = 'cd84cf951654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrasefullsearch', sa.Column('database', sa.String(), nullable=False))
    op.create_index(op.f('ix_phrasefullsearch_database'), 'phrasefullsearch', ['database'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasefullsearch_database'), table_name='phrasefullsearch')
    op.drop_column('phrasefullsearch', 'database')
    op.create_table('phrasethis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('database', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('search_volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competition', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_results', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='phrasethis_pkey')
    )
    op.create_index('ix_phrasethis_keyword', 'phrasethis', ['keyword'], unique=False)
    op.create_index('ix_phrasethis_database', 'phrasethis', ['database'], unique=False)
    # ### end Alembic commands ###
