"""Add column keyword_search in model PhraseRelated

Revision ID: 5bbbf62fd2a5
Revises: b94e0f1ddcba
Create Date: 2020-07-07 17:29:29.772397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbbf62fd2a5'
down_revision = 'b94e0f1ddcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phrasethis_database', table_name='phrasethis')
    op.drop_index('ix_phrasethis_keyword', table_name='phrasethis')
    op.drop_table('phrasethis')
    op.add_column('phraserelated', sa.Column('keyword_search', sa.String(), nullable=False))
    op.create_index(op.f('ix_phraserelated_keyword_search'), 'phraserelated', ['keyword_search'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phraserelated_keyword_search'), table_name='phraserelated')
    op.drop_column('phraserelated', 'keyword_search')
    op.create_table('phrasethis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('database', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('search_volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('competition', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_results', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='phrasethis_pkey')
    )
    op.create_index('ix_phrasethis_keyword', 'phrasethis', ['keyword'], unique=False)
    op.create_index('ix_phrasethis_database', 'phrasethis', ['database'], unique=False)
    # ### end Alembic commands ###
