"""Add column keyword_search in model PhraseRelated

Revision ID: 5bbbf62fd2a5
Revises: b94e0f1ddcba
Create Date: 2020-07-07 17:29:29.772397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbbf62fd2a5'
down_revision = 'b94e0f1ddcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phraserelated', sa.Column('keyword_search', sa.String(), nullable=False))
    op.create_index(op.f('ix_phraserelated_keyword_search'), 'phraserelated', ['keyword_search'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phraserelated_keyword_search'), table_name='phraserelated')
    op.drop_column('phraserelated', 'keyword_search')
    # ### end Alembic commands ###
