"""Remove column domain in model UrlOrganic

Revision ID: 6c2e49e6702d
Revises: 10245be06072
Create Date: 2020-07-16 18:27:29.705819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2e49e6702d'
down_revision = '10245be06072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_urlorganic_domain', table_name='urlorganic')
    op.drop_column('urlorganic', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urlorganic', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_urlorganic_domain', 'urlorganic', ['domain'], unique=False)
    # ### end Alembic commands ###
