"""Create model domain domains

Revision ID: 93975216e147
Revises: d91bb8ef389c
Create Date: 2020-07-14 20:33:10.710960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93975216e147'
down_revision = 'd91bb8ef389c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
