"""Add phrase_related model

Revision ID: 986843e6f199
Revises: c32e388a624b
Create Date: 2020-07-03 18:51:39.624329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986843e6f199'
down_revision = 'c32e388a624b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phraserelated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_results', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.DECIMAL(), nullable=False),
    sa.Column('competition', sa.Integer(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('trends', sa.String(), nullable=True),
    sa.Column('related_relevance', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phraserelated_database'), 'phraserelated', ['database'], unique=False)
    op.create_index(op.f('ix_phraserelated_id'), 'phraserelated', ['id'], unique=False)
    op.create_index(op.f('ix_phraserelated_keyword'), 'phraserelated', ['keyword'], unique=False)
    op.create_index(op.f('ix_phraserelated_trends'), 'phraserelated', ['trends'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phraserelated_trends'), table_name='phraserelated')
    op.drop_index(op.f('ix_phraserelated_keyword'), table_name='phraserelated')
    op.drop_index(op.f('ix_phraserelated_id'), table_name='phraserelated')
    op.drop_index(op.f('ix_phraserelated_database'), table_name='phraserelated')
    op.drop_table('phraserelated')
    # ### end Alembic commands ###
