"""Add column competition in model phrase_all

Revision ID: a0228fef1142
Revises: 986843e6f199
Create Date: 2020-07-03 18:52:44.361801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0228fef1142'
down_revision = '986843e6f199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phraseall', sa.Column('competition', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phraseall', 'competition')
    # ### end Alembic commands ###
