"""Add new models

Revision ID: a0c956333c0c
Revises: 31ea8fd8b1ea
Create Date: 2020-07-06 10:02:38.877963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c956333c0c'
down_revision = '31ea8fd8b1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
