"""Add new field database in model Adwords

Revision ID: b94e0f1ddcba
Revises: 57814115f909
Create Date: 2020-07-06 11:49:16.743847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94e0f1ddcba'
down_revision = '57814115f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phraseadwords', sa.Column('database', sa.String(), nullable=False))
    op.create_index(op.f('ix_phraseadwords_database'), 'phraseadwords', ['database'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phraseadwords_database'), table_name='phraseadwords')
    op.drop_column('phraseadwords', 'database')
    # ### end Alembic commands ###
