"""Add phrase_kdi model

Revision ID: befe121d7351
Revises: 28f41b39019e
Create Date: 2020-07-03 19:29:24.874114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befe121d7351'
down_revision = '28f41b39019e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrasekdi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('keyword_difficult_index', sa.DECIMAL(), nullable=True),
    sa.Column('database', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrasekdi_id'), 'phrasekdi', ['id'], unique=False)
    op.create_index(op.f('ix_phrasekdi_keyword'), 'phrasekdi', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasekdi_keyword'), table_name='phrasekdi')
    op.drop_index(op.f('ix_phrasekdi_id'), table_name='phrasekdi')
    op.drop_table('phrasekdi')
    # ### end Alembic commands ###
