"""Add phrase_this model

Revision ID: c42bfeca679e
Revises: 3eaa1e2dd2ee
Create Date: 2020-07-03 19:50:15.787377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42bfeca679e'
down_revision = '3eaa1e2dd2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
