"""Add new models

Revision ID: cd84cf951654
Revises: a0c956333c0c
Create Date: 2020-07-06 10:11:02.139877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd84cf951654'
down_revision = 'a0c956333c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrasethis',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('database', sa.String(), nullable=True),
                    sa.Column('keyword', sa.String(), nullable=False),
                    sa.Column('search_volume', sa.Integer(), nullable=False),
                    sa.Column('cpc', sa.Integer(), nullable=False),
                    sa.Column('competition', sa.Integer(), nullable=False),
                    sa.Column('competition', sa.Integer(), nullable=False),
                    sa.Column('number_results', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_phrasethis_database'), 'phrasethis', ['database'], unique=False)
    op.create_index(op.f('ix_phrasethis_keyword'), 'phrasethis', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasethis_keyword'), table_name='phrasethis')
    op.drop_index(op.f('ix_phrasethis_database'), table_name='phrasethis')
    op.drop_table('phraseorganic')
    # ### end Alembic commands ###