"""Add new models

Revision ID: cd84cf951654
Revises: a0c956333c0c
Create Date: 2020-07-06 10:11:02.139877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd84cf951654'
down_revision = 'a0c956333c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###