"""Add model UrlOrganic

Revision ID: d7b0ce083af0
Revises: db024a018a40
Create Date: 2020-07-16 17:52:19.826229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b0ce083af0'
down_revision = 'db024a018a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urlorganic',
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=False),
    sa.Column('cpc', sa.DECIMAL(), nullable=False),
    sa.Column('competition', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('traffic', sa.DECIMAL(), nullable=False),
    sa.Column('traffic_cost', sa.DECIMAL(), nullable=False),
    sa.Column('number_results', sa.BigInteger(), nullable=False),
    sa.Column('trends', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urlorganic_database'), 'urlorganic', ['database'], unique=False)
    op.create_index(op.f('ix_urlorganic_domain'), 'urlorganic', ['domain'], unique=False)
    op.create_index(op.f('ix_urlorganic_id'), 'urlorganic', ['id'], unique=False)
    op.create_index(op.f('ix_urlorganic_trends'), 'urlorganic', ['trends'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urlorganic_trends'), table_name='urlorganic')
    op.drop_index(op.f('ix_urlorganic_id'), table_name='urlorganic')
    op.drop_index(op.f('ix_urlorganic_domain'), table_name='urlorganic')
    op.drop_index(op.f('ix_urlorganic_database'), table_name='urlorganic')
    op.drop_table('urlorganic')
    # ### end Alembic commands ###
