"""Add model UrlOrganic

Revision ID: db024a018a40
Revises: c6721b288bc1
Create Date: 2020-07-16 17:51:18.330942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db024a018a40'
down_revision = 'c6721b288bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
