"""Add column serp_features in model UrlOrganic

Revision ID: fd37026d59fc
Revises: 227263f03676
Create Date: 2020-07-16 18:39:44.176681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd37026d59fc'
down_revision = '227263f03676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urlorganic', sa.Column('serp_features', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urlorganic', 'serp_features')
    # ### end Alembic commands ###
